name: example
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  super_toast:
    path: ../
    
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/icons/
 
  uses-material-design: true


